Map<String, dynamic> searchData = {
  "success": true,
  "query": "H",
  "results": {
    "products": [
      {
        "id": "65",
        "name": "XEAMUZY Travel Soap Holder Portable Soap Dish for ",
        "sku": "XEAMUZY-TRAVEL-SOAP-HOLDER",
        "image": "simple_main_0_69427e899d451.jpeg",
        "price": {"selling": 99, "mrp": 199, "discount_percentage": 50},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/65",
      },
      {
        "id": "64",
        "name": "M Y Multipurpose Metal Wall Shelf with 4 Hooks ",
        "sku": "MY-METAL-WALL-SHELF-4HOOK",
        "image": "simple_main_0_6942695a8d15a.jpeg",
        "price": {"selling": 399, "mrp": 999, "discount_percentage": 60},
        "stock": {"quantity": 20, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/64",
      },
      {
        "id": "63",
        "name": "ESSPY Wall Mounted Toothbrush Holder for Bathroom ",
        "sku": "ESSPY-TOOTHBRUSH-HOLDER-WALL",
        "image": "simple_main_0_6942682b8a31e.jpeg",
        "price": {"selling": 129, "mrp": 249, "discount_percentage": 48},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/63",
      },
      {
        "id": "62",
        "name": "PLUTOHOME Fish Shape Cute Adhesive Waterproof Wall",
        "sku": "PLUTO-FISH-SOAP-DISH-4PC",
        "image": "simple_main_0_694266dba3a19.jpeg",
        "price": {"selling": 249, "mrp": 599, "discount_percentage": 58},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/62",
      },
      {
        "id": "61",
        "name": "WINGER Wall Mounted Toothbrush Holder for Bathroom",
        "sku": "WINGER-TOOTHBRUSH-HOLDER-WALL",
        "image": "simple_main_0_69426510a6ab3.jpeg",
        "price": {"selling": 149, "mrp": 299, "discount_percentage": 50},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/61",
      },
      {
        "id": "60",
        "name": "KYASO Pack of 4 Wall Mount Bathroom Shelf and Soap",
        "sku": "KYASO-BATH-SHELF-4PC-WHT",
        "image": "simple_main_0_694263701a0b0.jpeg",
        "price": {"selling": 299, "mrp": 799, "discount_percentage": 63},
        "stock": {"quantity": 20, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": null,
        "relevance_score": 50,
        "url": "/detail/60",
      },
      {
        "id": "59",
        "name": "Zenzone Wall Mount Bathroom Corner and Soap Rack ",
        "sku": "BATH-ZENZONE-CORNER-RACK",
        "image": "simple_main_0_694261034a947.jpeg",
        "price": {"selling": 190, "mrp": 499, "discount_percentage": 62},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": "GREENBERRI",
        "relevance_score": 50,
        "url": "/detail/59",
      },
      {
        "id": "57",
        "name": "XBEY Plastic Toothbrush Holder  (White, Wall Mount)",
        "sku": "1234",
        "image": "simple_main_0_691eb50cc3e8a.jpg",
        "price": {"selling": 272, "mrp": 999, "discount_percentage": 73},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": "GREENBERRI",
        "relevance_score": 50,
        "url": "/detail/57",
      },
      {
        "id": "58",
        "name": "Men Regular Fit Self Design Button Down Collar Cas",
        "sku": "RED-SHIRT",
        "image": "",
        "price": {"selling": 0, "mrp": 0, "discount_percentage": 0},
        "stock": {"quantity": 10, "status": "in_stock", "unit": "1"},
        "category": "APPLIANCES",
        "brand": "GREENBERRI",
        "relevance_score": 40,
        "url": "/detail/58",
      },
    ],
    "total": 9,
    "page": 1,
    "limit": 24,
    "total_pages": 1,
    "showing_from": 1,
    "showing_to": 9,
  },
  "filters": {
    "categories": [
      {"id": "288", "name": "APPLIANCES", "count": 9},
    ],
    "brands": [
      {"id": "46", "name": "GREENBERRI", "count": 3},
    ],
    "price_range": {"min": 0, "max": 99},
  },
  "sort": "relevance",
};
